### ISSUE TITLE
CCP4 7.1 still required

### ISSUE THREAD

**Issue by james-vincent** [rlkingston/IPA#2]
Since newer versions of CCP4 are now available can the clipper library from these be used instead of 7.1?

**Comment by rlkingston** [comment]
If you can get  a newer version to compile then I think it should work. I don't think there have been any changes to the clipper library since version 7.1 of CCP4 which would cause problems for IPA.  Note that CCP4 v8.0 (Adddingham) does not compile on Macs with the new arm64 (M1/M2) chip architecture. Apparently that's going to be fixed with the upcoming release. We are aiming for a new release of IPA in 4-6 weeks time, which has many improvements. That will be tested against the CCP4 v8 library. If the compilation issues haven't been resolved, we will try and post some statically linked binaries then.

**Comment by james-vincent** [comment]
Thanks for the update and quick reply.

Jim

James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --

**Comment by rlkingston** [comment]
No problem. Note that IPA can be compiled and run under Linux but we haven't tested it exhaustively there, and there are some reported issues with random number generation (every run turns out the same). And probably other things we don't know about :-)  Something else that's on the to-do list.

**Comment by james-vincent** [comment]
Great - thanks for the quick reply.

Jim


James Vincent, PhD
Bioinformatics Software Curator
Dept. of BCMP, Harvard Medical School
— BioGrids.org --
